# Generated by Django 5.2.2 on 2025-06-08 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('normal', 'Normal Page'), ('landing', 'Landing Page')], default='normal', max_length=10)),
                ('desp1', models.TextField(blank=True, help_text='First description paragraph')),
                ('desp2', models.TextField(blank=True, help_text='Second description paragraph')),
                ('philosophy_title', models.CharField(blank=True, max_length=200)),
                ('title1_heading', models.CharField(blank=True, max_length=200)),
                ('title1_desp1', models.TextField(blank=True)),
                ('title1_desp2', models.TextField(blank=True)),
                ('title1_image', models.ImageField(blank=True, null=True, upload_to='about/landing/')),
                ('title2_heading', models.CharField(blank=True, max_length=200)),
                ('title2_desp1', models.TextField(blank=True)),
                ('title2_desp2', models.TextField(blank=True)),
                ('title2_image', models.ImageField(blank=True, null=True, upload_to='about/landing/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('treatment_interest', models.CharField(blank=True, help_text="Treatment they're interested in", max_length=200)),
                ('message', models.TextField(blank=True, help_text='Additional message or concerns')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landing Page FAQ',
                'verbose_name_plural': 'Landing Page FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('static', 'Static Image'), ('carousel', 'Image Carousel')], default='static', max_length=10)),
                ('static_image', models.ImageField(blank=True, help_text='Single background image for landing page', null=True, upload_to='landing/bg/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Background',
                'verbose_name_plural': 'Landing Page Backgrounds',
            },
        ),
        migrations.CreateModel(
            name='PhilosophyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(help_text='Skin condition treated', max_length=200)),
                ('duration', models.CharField(help_text='Treatment duration or timeline', max_length=100)),
                ('description', models.TextField()),
                ('before_image', models.ImageField(upload_to='results/before/')),
                ('after_image', models.ImageField(upload_to='results/after/')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on landing page')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Monalisa Wellness', max_length=100)),
                ('site_tagline', models.CharField(blank=True, max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('business_hours', models.TextField(blank=True, help_text='Business hours information')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(help_text='Icon for the concern', upload_to='skin_concerns/icons/')),
                ('treatments', models.TextField(help_text='Related treatments information')),
                ('products', models.TextField(help_text='Recommended products information')),
                ('results', models.TextField(help_text='Expected results information')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Treatment Category',
                'verbose_name_plural': 'Treatment Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Treatment FAQ',
                'verbose_name_plural': 'Treatment FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='landing/carousel/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('landing_bg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='api.landingpagebg')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text="e.g., '60 minutes', '1-2 hours'", max_length=50)),
                ('price', models.CharField(help_text="e.g., '$150', 'From $100'", max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='treatments/')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on landing page')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.treatmentcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
