# Generated by Django 4.2 on 2025-07-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blog_blogimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Treatment Benefit",
                "verbose_name_plural": "Treatment Benefits",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("step_number", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Treatment Step",
                "verbose_name_plural": "Treatment Steps",
                "ordering": ["order", "step_number"],
            },
        ),
    ]
