# Generated by Django 4.2 on 2025-07-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_treatmentbenefit_treatmentstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentbenefit",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="api.treatment",
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="api.treatment",
            ),
        ),
    ]
