# Generated by Django 4.2 on 2025-07-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_treatmentbenefit_treatment_treatmentstep_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentbenefit",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="api.treatment",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentstep",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="api.treatment",
            ),
        ),
    ]
