# Generated by Django 4.2 on 2025-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_treatmentbenefit_treatment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("clock", "Clock (Years of Experience)"),
                            ("award", "Award (Personalized Plans)"),
                            ("zap", "Zap (Advanced Technology)"),
                            ("heart", "Heart (Proven Results)"),
                            ("shield", "Shield"),
                            ("star", "Star"),
                            ("users", "Users"),
                            ("check-circle", "Check Circle"),
                        ],
                        default="clock",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Why Choose Us Benefit",
                "verbose_name_plural": "Why Choose Us Benefits",
                "ordering": ["order"],
            },
        ),
    ]
