# Generated by Django 4.2 on 2025-07-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_whychooseus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "specialization",
                    models.CharField(help_text="Services offered", max_length=300),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the clinic"),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "reviews_text",
                    models.CharField(default="Google reviews", max_length=100),
                ),
                (
                    "business_hours",
                    models.CharField(
                        default="Open Daily - Closes 7:30 PM", max_length=100
                    ),
                ),
                (
                    "hours_note",
                    models.CharField(
                        default="Call for specific timings", max_length=100
                    ),
                ),
                ("main_image", models.ImageField(upload_to="clinics/main/")),
                (
                    "google_maps_url",
                    models.URLField(help_text="Google Maps link for directions"),
                ),
                (
                    "map_embed_url",
                    models.URLField(blank=True, help_text="Google Maps embed URL"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="clinics/team/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="api.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Team Member",
                "verbose_name_plural": "Clinic Team Members",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="clinics/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Image",
                "verbose_name_plural": "Clinic Images",
                "ordering": ["order"],
            },
        ),
    ]
