# Generated by Django 4.2 on 2025-07-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_clinic_clinicteammember_clinicimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.clinic",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="api.clinic",
            ),
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.CharField(help_text="Offer headline/title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the offer"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Offer promotional image", upload_to="offers/"
                    ),
                ),
                ("valid_from", models.DateField(help_text="Offer start date")),
                ("valid_until", models.DateField(help_text="Offer end date")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured offer on clinic page"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="api.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
