# Generated by Django 4.2 on 2025-07-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_appointment_clinic_treatment_clinic_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of contact email addresses as JSON array. Example: ["info@example.com", "support@example.com"]',
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_phones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of contact phone numbers as JSON array. Example: ["+1-555-0123", "+1-555-0124"]',
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="business_hours",
            field=models.TextField(
                blank=True,
                help_text="Business hours information. Use full format like 'Monday-Friday: 9:00 AM - 7:30 PM' to avoid formatting issues.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Legacy field - use contact_emails instead",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use contact_phones instead",
                max_length=20,
            ),
        ),
    ]
