# Generated by Django 4.2.10 on 2025-10-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_update_sitesettings_multiple_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='price',
        ),
        migrations.CreateModel(
            name='TreatmentClinicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text="e.g., '$150', 'From $100'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for this clinic')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_pricing', to='api.clinic')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_pricing', to='api.treatment')),
            ],
            options={
                'verbose_name': 'Treatment Clinic Pricing',
                'verbose_name_plural': 'Treatment Clinic Pricing',
                'ordering': ['order', 'clinic__name'],
                'unique_together': {('treatment', 'clinic')},
            },
        ),
    ]
