# Generated by Django 5.1.14 on 2025-12-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_treatment_clinic_remove_treatment_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="offers_strip_color",
            field=models.CharField(
                default="#DC2626",
                help_text="Color for the offers strip banner (hex code, e.g., #DC2626 for red, #1F2937 for dark gray). Default: #DC2626 (red)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="offers_strip_gradient_color",
            field=models.CharField(
                blank=True,
                default="#B91C1C",
                help_text="Optional gradient color for the offers strip (hex code). If left blank, will use a darker shade of the main color.",
                max_length=7,
            ),
        ),
    ]
