# Generated by Django 5.1.14 on 2025-12-25 19:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_sitesettings_offers_strip_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="phone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="offers_strip_color",
            field=colorfield.fields.ColorField(
                default="#DC2626",
                help_text="Color for the offers strip banner. Default: #DC2626 (red)",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="offers_strip_gradient_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#B91C1C",
                help_text="Optional gradient color for the offers strip. If left blank, will use a darker shade of the main color.",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
